SecondFileSystem : myshell.o filesystem.o cmd.o
	g++ -o SecondFileSystem myshell.o filesystem.o cmd.o


myshell.o : myshell.cpp 
	g++ -c myshell.cpp

cmd.o : cmd.cpp 
	g++ -c cmd.cpp

filesystem.o : filesystem.cpp 
	g++ -c filesystem.cpp
